### ISSUE TITLE
Able to run vta example with race_condition branch

### ISSUE THREAD

**Issue by chauhanjoy** [antmicro/alkali-csd-projects#20]
Hi

I am able to run VTA test example on AN-300 board using race_condition branch.

**Comment by tmichalak** [comment]
Hi @chauhanjoy did you use the artifacts from the [CI](https://github.com/antmicro/alkali-csd-projects/actions/runs/3097596894) or did you build it locally?

**Comment by chauhanjoy** [comment]
I have build the branch locally

**Comment by hardikvala** [comment]
Hi,

I have attached vta example working log.

[example_code_race_condition_CI_log.txt](https://github.com/antmicro/alkali-csd-projects/files/9777089/example_code_race_condition_CI_log.txt)

**Comment by rw1nkler** [comment]
Thank you for the attached logs. The `race_condition` branch has been merged into `main`
