### ISSUE TITLE
Got firmware error on "make firmware/all" command

### ISSUE THREAD

**Issue by hardikvala** [antmicro/alkali-csd-projects#24]
Hi,

I am following the below steps: 

```
  1.  git clone https://github.com/antmicro/alkali-csd-projects.git -b race_condition
  2.  cd alkali-csd-projects/
  3.  git submodule update --init --recursive
  4.  docker pull antmicro/alkali
  5.  make enter
  6.  export BOARD=an300 (inside container)
  7.  make firmware/all
  ```
I have attached the error .PNG. 
![Screenshot from 2022-10-18 13-47-00](https://user-images.githubusercontent.com/8392420/196377271-65107d32-97af-4790-96af-4c7e9d87b407.png)

**Comment by rw1nkler** [comment]
@hardikvala  please use the main branch of the repository. The `race_condition` branch has been merged into the `main` branch and your problem has been resolved there.
