### ISSUE TITLE
make docker command failed to build docker image

### ISSUE THREAD

**Issue by chauhanjoy** [antmicro/alkali-csd-projects#3]
Hi,

**make docker** command not worked. 
here I have attached full log.
[make_docker_log.txt](https://github.com/antmicro/alkali-csd-projects/files/9574442/make_docker_log.txt)

**Comment by rw1nkler** [comment]
Hi @chauhanjoy,

fix is already in https://github.com/antmicro/alkali-csd-projects/pull/2 and will be merged soon

For now please download the docker image directly from DockerHub using:
```
docker pull antmicro/alkali
```

**Comment by rw1nkler** [comment]
Hi @chauhanjoy, 

the problems with building docker image should be resolved. Can you try once again, and confirm that it works for you?
